global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s

# Alertmanager configuration
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      - alertmanager:9093

# Load rules from file
rule_files:
  - "alert_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'sample-api'
    metrics_path: '/metrics'
    file_sd_configs:
      - files:
          - '/etc/prometheus/targets.json'
    scrape_interval: 5s
    
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']