receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024
  
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
    spike_limit_mib: 200
  
  # Add span processing for better data quality
  attributes:
    actions:
      - key: environment
        value: dev
        action: insert

exporters:
  logging:
    verbosity: detailed
  
  prometheus:
    endpoint: 0.0.0.0:8889
    namespace: otel
    send_timestamps: true
    metric_expiration: 180m
  
  otlp/tempo:
    endpoint: tempo:4317
    tls:
      insecure: true
  
  # Forwarding traces to Tempo in OTLP format
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, batch, attributes]
      exporters: [otlp]
    
    metrics:
      receivers: [otlp]
      processors: [memory_limiter, batch]
      exporters: [prometheus]
  
  telemetry:
    logs:
      level: info
    metrics:
      address: 0.0.0.0:8888