apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      exemplarTraceIdDestinations:
        - name: TraceID
          datasourceUid: tempo
          urlDisplayLabel: 'View trace in Tempo'
          
  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - name: TraceID
          matcherRegex: "traceID[\"=:\\s]+(\\w+)"
          url: $${__value.raw}
          datasourceUid: tempo
          urlDisplayLabel: "View Trace in Tempo"

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    uid: tempo
    jsonData:
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: -300ms
        spanEndTimeShift: 300ms
        tags: ['traceID']
        filterByTraceID: true
        filterBySpanID: false